# Generated by Django 2.0.2 on 2018-03-30 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SelectGame', '0002_event_notifications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='notifications',
            field=models.ManyToManyField(related_name='event', to='Social.Notification'),
        ),
    ]
