# Generated by Django 2.0.2 on 2018-02-15 12:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('SelectGame', '0002_auto_20180212_1608'),
    ]

    operations = [
        migrations.CreateModel(
            name='model_location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100, verbose_name='address')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Address',
                'verbose_name': 'Address',
            },
        ),
        migrations.CreateModel(
            name='model_rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'ratings',
                'verbose_name': 'rating',
            },
        ),
        migrations.AlterModelOptions(
            name='model_game',
            options={'verbose_name': 'game', 'verbose_name_plural': 'games'},
        ),
        migrations.AddField(
            model_name='model_rating',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SelectGame.model_game'),
        ),
        migrations.AddField(
            model_name='model_rating',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
