# Generated by Django 2.0.2 on 2018-02-20 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SelectGame', '0003_auto_20180215_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model_category',
            name='name',
            field=models.CharField(max_length=30, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='model_game',
            name='name',
            field=models.CharField(max_length=30, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='model_rating',
            name='rating',
            field=models.IntegerField(verbose_name='rating'),
        ),
    ]
