# Generated by Django 2.0.2 on 2018-03-31 17:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('SelectGame', '0004_auto_20180331_1723'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='owner',
        ),
        migrations.AddField(
            model_name='event',
            name='creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='event_creator', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventparticipant',
            name='role',
            field=models.CharField(choices=[('WC', 'Will come'), ('MA', 'Maybe'), ('NC', 'Not coming'), ('PE', 'Pending')], default='PA', max_length=2),
        ),
        migrations.AlterField(
            model_name='eventparticipant',
            name='status',
            field=models.CharField(choices=[('WC', 'Will come'), ('MA', 'Maybe'), ('NC', 'Not coming'), ('PE', 'Pending')], default='NC', max_length=2),
        ),
    ]
