# Generated by Django 2.0.2 on 2018-02-20 17:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('SelectGame', '0004_auto_20180220_1727'),
    ]

    operations = [
        migrations.CreateModel(
            name='model_event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='date')),
                ('is_public', models.BooleanField(verbose_name='public')),
                ('games', models.ManyToManyField(to='SelectGame.model_game', verbose_name='games')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SelectGame.model_location', verbose_name='location')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_owner', to=settings.AUTH_USER_MODEL)),
                ('participants', models.ManyToManyField(related_name='event_participants', to=settings.AUTH_USER_MODEL, verbose_name='participants')),
            ],
            options={
                'verbose_name': 'event',
                'verbose_name_plural': 'events',
            },
        ),
    ]
