# Generated by Django 2.0.2 on 2018-02-23 20:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('SelectGame', '0005_model_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='model_game_library',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('games', models.ManyToManyField(to='SelectGame.model_game', verbose_name='games')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_owner', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'games',
                'verbose_name': 'game',
            },
        ),
    ]
