# Generated by Django 2.0.2 on 2018-03-31 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SelectGame', '0005_auto_20180331_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventparticipant',
            name='glyphicon',
            field=models.CharField(default='glyphicon glyphicon-user text-primary', max_length=100),
        ),
        migrations.AlterField(
            model_name='eventparticipant',
            name='role',
            field=models.CharField(choices=[('OW', 'Owner'), ('PA', 'Participant')], default='PA', max_length=2),
        ),
        migrations.AlterField(
            model_name='eventparticipant',
            name='status',
            field=models.CharField(choices=[('WC', 'Will come'), ('MA', 'Maybe'), ('NC', 'Not coming'), ('PE', 'Pending')], default='PE', max_length=2),
        ),
    ]
