# Generated by Django 2.0.2 on 2018-02-23 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SelectGame', '0006_model_game_library'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='model_game_library',
            options={'verbose_name': 'game library', 'verbose_name_plural': 'game library'},
        ),
        migrations.AlterField(
            model_name='model_game',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Comment'),
        ),
    ]
