# Generated by Django 2.0.2 on 2018-04-01 08:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SelectGame', '0007_auto_20180331_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamelibrary',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='games', to=settings.AUTH_USER_MODEL),
        ),
    ]
