# Generated by Django 2.0.2 on 2018-02-24 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SelectGame', '0007_auto_20180223_2108'),
    ]

    operations = [
        migrations.AddField(
            model_name='model_rating',
            name='review',
            field=models.TextField(blank=True, verbose_name='review'),
        ),
    ]
