# Generated by Django 2.0.2 on 2018-02-24 16:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SelectGame', '0008_model_rating_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model_rating',
            name='rating',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)], verbose_name='rating'),
        ),
    ]
