# Generated by Django 2.0.2 on 2018-04-01 08:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('SelectGame', '0008_auto_20180401_0813'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='EventGameVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='SelectGame.EventGame')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'event game vote',
                'verbose_name_plural': 'event game votes',
            },
        ),
        migrations.RemoveField(
            model_name='event',
            name='games',
        ),
        migrations.AddField(
            model_name='eventgame',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to='SelectGame.Event'),
        ),
        migrations.AddField(
            model_name='eventgame',
            name='games',
            field=models.ManyToManyField(to='SelectGame.Game'),
        ),
        migrations.AlterUniqueTogether(
            name='eventgamevote',
            unique_together={('event_game', 'user')},
        ),
    ]
