# Generated by Django 2.0.2 on 2018-02-25 06:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SelectGame', '0009_auto_20180224_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model_rating',
            name='rating',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)], verbose_name='rating'),
        ),
    ]
