# Generated by Django 2.0.2 on 2018-04-01 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SelectGame', '0010_auto_20180401_0824'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventgame',
            name='games',
        ),
        migrations.AddField(
            model_name='eventgame',
            name='game',
            field=models.ManyToManyField(to='SelectGame.Game'),
        ),
    ]
