# Generated by Django 2.0.2 on 2018-02-25 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Social', '0002_auto_20180225_1044'),
        ('SelectGame', '0010_auto_20180225_0724'),
    ]

    operations = [
        migrations.AddField(
            model_name='model_event',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Social.model_group'),
        ),
    ]
