# Generated by Django 2.0.2 on 2018-04-01 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SelectGame', '0011_auto_20180401_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventgame',
            name='event',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='games', to='SelectGame.Event'),
        ),
    ]
