# Generated by Django 2.0.2 on 2018-02-26 19:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SelectGame', '0011_model_event_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model_game_library',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
