# Generated by Django 2.0.2 on 2018-02-27 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SelectGame', '0012_auto_20180226_2000'),
    ]

    operations = [
        migrations.AddField(
            model_name='model_game',
            name='image',
            field=models.ImageField(null=True, upload_to='uploads/game_images'),
        ),
    ]
