# Generated by Django 2.0.2 on 2018-04-01 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SelectGame', '0012_auto_20180401_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventgame',
            name='average',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='eventgame',
            name='number_of_rated',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='eventgame',
            name='too_low',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='eventgame',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to='SelectGame.Event'),
        ),
        migrations.RemoveField(
            model_name='eventgame',
            name='game',
        ),
        migrations.AddField(
            model_name='eventgame',
            name='game',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='SelectGame.Game'),
            preserve_default=False,
        ),
    ]
