# Generated by Django 2.0.2 on 2018-04-01 11:46

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('SelectGame', '0013_auto_20180401_1140'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='eventgamevote',
            unique_together={('event_game', 'user')},
        ),
    ]
