# Generated by Django 2.0.2 on 2018-03-03 13:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SelectGame', '0014_auto_20180303_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model_event',
            name='games',
            field=models.ManyToManyField(blank=True, to='SelectGame.model_game', verbose_name='games'),
        ),
        migrations.AlterField(
            model_name='model_event',
            name='participants',
            field=models.ManyToManyField(blank=True, null=True, related_name='event_participants', to=settings.AUTH_USER_MODEL, verbose_name='participants'),
        ),
    ]
