# Generated by Django 2.0.2 on 2018-04-01 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SelectGame', '0014_auto_20180401_1146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventgamevote',
            name='game',
        ),
    ]
