# Generated by Django 2.0.2 on 2018-04-15 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SelectGame', '0015_remove_eventgamevote_game'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventparticipant',
            name='glyphicon',
            field=models.CharField(default="material-icons event_status_pending'", max_length=100),
        ),
    ]
