# Generated by Django 2.0.2 on 2018-03-09 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Social', '0008_auto_20180303_1447'),
        ('SelectGame', '0015_auto_20180303_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='model_event',
            name='messages',
            field=models.ManyToManyField(to='Social.model_message'),
        ),
    ]
