# Generated by Django 2.0.2 on 2018-03-09 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SelectGame', '0016_model_event_messages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model_event',
            name='messages',
            field=models.ManyToManyField(null=True, to='Social.model_message'),
        ),
    ]
