# Generated by Django 2.0.2 on 2018-03-11 09:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SelectGame', '0018_auto_20180309_2149'),
    ]

    operations = [
        migrations.AddField(
            model_name='model_game',
            name='maximum_number_of_players',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='maximum number of players'),
        ),
        migrations.AddField(
            model_name='model_game',
            name='minimum_number_of_players',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='minimum number of players'),
        ),
    ]
