# Generated by Django 2.0.2 on 2018-03-11 09:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SelectGame', '0019_auto_20180311_0920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model_event',
            name='messages',
            field=models.ManyToManyField(blank=True, to='Social.model_message'),
        ),
        migrations.AlterField(
            model_name='model_event',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='event_participants', to=settings.AUTH_USER_MODEL, verbose_name='participants'),
        ),
    ]
