# Generated by Django 2.0.2 on 2018-03-11 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SelectGame', '0021_auto_20180311_0923'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='model_category',
            options={'ordering': ['name'], 'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
        migrations.AddField(
            model_name='model_game',
            name='link',
            field=models.URLField(blank=True, verbose_name='link'),
        ),
    ]
