# Generated by Django 2.0.2 on 2018-03-11 18:37

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('SelectGame', '0023_auto_20180311_1754'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='model_rating',
            unique_together={('game', 'user')},
        ),
    ]
