# Generated by Django 2.0.2 on 2018-03-07 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='model_accordion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=100, verbose_name='header')),
            ],
            options={
                'verbose_name': 'accordion',
                'verbose_name_plural': 'accordions',
            },
        ),
        migrations.CreateModel(
            name='model_link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=100, verbose_name='link')),
                ('text', models.CharField(max_length=30, verbose_name='text')),
            ],
            options={
                'verbose_name': 'link',
                'verbose_name_plural': 'links',
            },
        ),
        migrations.AddField(
            model_name='model_accordion',
            name='links',
            field=models.ManyToManyField(to='Frontend.model_link', verbose_name='links'),
        ),
    ]
