# Generated by Django 2.0.2 on 2018-03-07 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0002_model_link_authenticated'),
    ]

    operations = [
        migrations.AddField(
            model_name='model_accordion',
            name='glyphicon',
            field=models.CharField(max_length=100, null=True, verbose_name='glyphicon'),
        ),
        migrations.AddField(
            model_name='model_link',
            name='glyphicon',
            field=models.CharField(max_length=100, null=True, verbose_name='glyphicon'),
        ),
    ]
