# Generated by Django 2.0.2 on 2018-03-07 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0004_auto_20180307_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model_accordion',
            name='glyphicon',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='glyphicon'),
        ),
    ]
