# Generated by Django 2.0.2 on 2018-02-25 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Social', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='model_group_message',
            options={'verbose_name': 'group message', 'verbose_name_plural': 'group messages'},
        ),
    ]
