# Generated by Django 2.0.2 on 2018-02-25 10:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Social', '0002_auto_20180225_1044'),
    ]

    operations = [
        migrations.CreateModel(
            name='model_friends',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pe', 'pending approval'), ('ac', 'accepted'), ('re', 'rejected'), ('rm', 'removed')], default='pe', max_length=2)),
                ('user1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='User1', to=settings.AUTH_USER_MODEL)),
                ('user2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='User2', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'friend',
                'verbose_name_plural': 'friends',
            },
        ),
        migrations.CreateModel(
            name='model_private_message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('messages', models.ManyToManyField(to='Social.model_message')),
                ('participants', models.ManyToManyField(related_name='participants', to=settings.AUTH_USER_MODEL, verbose_name='participants')),
            ],
            options={
                'verbose_name': 'private message',
                'verbose_name_plural': 'private messages',
            },
        ),
        migrations.AlterField(
            model_name='model_group',
            name='members',
            field=models.ManyToManyField(related_name='group_members', to=settings.AUTH_USER_MODEL, verbose_name='members'),
        ),
    ]
