# Generated by Django 2.0.2 on 2018-02-25 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Social', '0003_auto_20180225_1140'),
    ]

    operations = [
        migrations.RenameField(
            model_name='model_friends',
            old_name='status',
            new_name='status_user1',
        ),
        migrations.AddField(
            model_name='model_friends',
            name='status_user2',
            field=models.CharField(choices=[('pe', 'pending approval'), ('ac', 'accepted'), ('re', 'rejected'), ('rm', 'removed')], default='pe', max_length=2),
        ),
    ]
