# Generated by Django 2.0.2 on 2018-02-25 10:45

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Social', '0004_auto_20180225_1143'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='model_friends',
            unique_together={('user1', 'user2')},
        ),
    ]
