# Generated by Django 2.0.2 on 2018-03-30 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Social', '0004_auto_20180329_2104'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='notification',
            field=models.ManyToManyField(related_name='group', to='Social.Notification', verbose_name='notification'),
        ),
        migrations.AlterField(
            model_name='usermessage',
            name='notification',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='message', to='Social.Notification', verbose_name='notification'),
        ),
    ]
