# Generated by Django 2.0.2 on 2018-02-27 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Social', '0005_auto_20180225_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='model_user_profile',
            name='avatar',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
