# Generated by Django 2.0.2 on 2018-02-27 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Social', '0006_model_user_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model_user_profile',
            name='avatar',
            field=models.ImageField(null=True, upload_to='uploads/avatars'),
        ),
    ]
