# Generated by Django 2.0.2 on 2018-03-03 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Social', '0007_auto_20180227_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model_user_profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/avatars'),
        ),
        migrations.AlterField(
            model_name='model_user_profile',
            name='biography',
            field=models.TextField(blank=True, null=True, verbose_name='biography'),
        ),
    ]
