# Generated by Django 2.0.2 on 2018-03-10 08:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Social', '0009_model_message_writer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model_message',
            name='writer',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
