# Generated by Django 2.0.2 on 2018-03-10 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Social', '0010_auto_20180310_0832'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='model_message',
            options={'ordering': ['-created_date'], 'verbose_name': 'message', 'verbose_name_plural': 'messages'},
        ),
    ]
