# Generated by Django 2.0.2 on 2018-03-10 22:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Social', '0011_auto_20180310_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model_message',
            name='writer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
