# Generated by Django 2.0.2 on 2018-03-13 17:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Social', '0012_auto_20180310_2226'),
    ]

    operations = [
        migrations.CreateModel(
            name='model_friend_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Friend list',
                'verbose_name_plural': 'Friend list',
            },
        ),
        migrations.CreateModel(
            name='model_relationsship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pe', 'pending approval'), ('ac', 'accepted'), ('re', 'rejected'), ('rm', 'removed')], default='pe', max_length=2)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Relationship status',
                'verbose_name_plural': 'Relationship status',
            },
        ),
        migrations.AlterUniqueTogether(
            name='model_friends',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='model_friends',
            name='user1',
        ),
        migrations.RemoveField(
            model_name='model_friends',
            name='user2',
        ),
        migrations.DeleteModel(
            name='model_friends',
        ),
        migrations.AddField(
            model_name='model_friend_list',
            name='friends',
            field=models.ManyToManyField(to='Social.model_relationsship'),
        ),
        migrations.AddField(
            model_name='model_friend_list',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
