# Generated by Django 2.0.2 on 2018-03-14 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Social', '0013_auto_20180313_1859'),
    ]

    operations = [
        migrations.CreateModel(
            name='model_friends',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_from', to='Social.model_relationsship')),
                ('user_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_to', to='Social.model_relationsship')),
            ],
            options={
                'verbose_name_plural': 'Friends',
                'verbose_name': 'Friend',
            },
        ),
        migrations.RemoveField(
            model_name='model_friend_list',
            name='friends',
        ),
        migrations.RemoveField(
            model_name='model_friend_list',
            name='user',
        ),
        migrations.DeleteModel(
            name='model_friend_list',
        ),
    ]
